Add unit test fixes for python3
The relay.py script was decoding utf-8 when it didn't need to.  This
caused compat problems when running the unit tests in python3:

	AttributeError: 'str' object has no attribute 'decode'
With this patch, the unit tests for python 2.7 and 3.4 pass.

validate_script: fix python 3.4 issue in script.

Litterals in python3 need to be cast to binary.  This patch fixes:
	TypeError: a bytes-like object is required, not 'str'

test_cases.py: fix assert check where the framework may return out of order

Fix the following error:
>       assert result == (0, "command: ['cmd', '--v=val', '--t']  ,
>       stdout:   ,  stderr: ")

E       AssertionError: assert (0, "command:... ,  stderr: ") == (0, "command: ... ,  stderr: ")
E         At index 1 diff: "command: ['cmd', '--t', '--v=val']  , stdout:   ,  stderr: " != "command: ['cmd', '--v=val', '--t']  , stdout:   ,  stderr: "
E         Use -v to get the full diff

travis.yml: add python 3.4

Validate python 3.4 as well.

Signed-off-by: Paul Barrette <paulbarrette@gmail.com>